### ISSUE TITLE
terminalCloudApi async response type

### ISSUE THREAD

**Issue by khaledbenbouali** [Adyen/adyen-node-api-library#1036]
We found that terminalCloudApi.async(terminalApiRequest) type : Promise< string > ,
but when you try to set fault value , ex ServiceID containe point like "1234..56" in this case the response come with type  "TerminalApiResponse" not string 

![image](https://user-images.githubusercontent.com/116771232/200627941-d65eabf4-62ee-4e5d-9c5f-58413599a3e2.png)

**Comment by wboereboom** [comment]
Hi @khaledbenbouali ,

Thank you for raising this issue. Our [documentation](https://docs.adyen.com/point-of-sale/terminal-api#request-message-header) states that the ServiceID should only contain alphanumeric values. 
Are you sure using  characters like `.` isn't simply throwing errors due to its invalid value?

If not, can you share the response?

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Hi @wboereboom ,

After consulting our POS department they have assured me that for cloud integration the `ServiceID` should only contain alphanumeric characters.
Unfortunately our API does not yet properly convey that in its response, that's some homework on our part.

For local integrations using non-alphanumeric characters in the `ServiceID` is not a problem and you should be able to use those without any problems.

Kind Regards,
Wouter
Adyen
