### ISSUE TITLE
[BUG] Checkout API-Typings is not v70 ./. Typings for PaymentRequest are not up to date

### ISSUE THREAD

**Issue by stefanmichalk** [Adyen/adyen-node-api-library#1210]
### **Typings for PaymentRequest are not up to date**

On February 17th, 2023 you released v13.0.0 and said, the Checkout API supports now v70.
The current API-Documentation for Checkout / Payment is v70 [as seen here](https://docs.adyen.com/api-explorer/Checkout/70/post/payments).

In the documentation you marked `deliveryDate` as deprecated and ask us to use `deliveryAt` instead. Absolutely fine.

But till now, your typings don't let us use `deliveryAt` [as you can see here (search for it).](https://github.com/Adyen/adyen-node-api-library/blob/develop/src/typings/checkout/paymentRequest.ts).

In the `client.ts` you changed the version from 69 to 70 [seen here](https://github.com/Adyen/adyen-node-api-library/blob/c415b06014cbcc1dd25c50208f3d420398e349cf/src/client.ts) which makes us believe, we use v70.

Actually we can't without annotating it with `@ts-ignore` - which I told my team is not allowed.

**Comment by wboereboom** [comment]
Hi @stefanmichalk,

Thanks for creating this issue. I'm sorry to hear about the the blocker this is causing your team.
Our Library has not yet been updated with this field (though it will surely be there in the next release, I've checked).
We allow the introduction of new fields in existing API versions as we do not consider those to be breaking changes. It might very well be the case that this deprecation was introduced after the release of Checkout v70.

As long as you are on v70, it is perfectly valid to keep using deliveryDate. This field will not be removed in v70. It will most likely not be there in v71, which would likely cause a new major version of the API library either way.

The options I can provide you at this time are:
1. Wait until we are ready to release a new version of our library, which will be v14 due to various model name updates throughout Checkout API. I expect us to be ready for release within a few weeks time.
2. Keep using `deliveryDate` until you do another upgrade, or when you move to v71

I hope this helps to alleviate some of your worries. I apologise for any inconvenience this might have caused.

Kind Regards,
Wouter
Adyen

**Comment by stefanmichalk** [comment]
Hello Wouter,

thank you very much for your answer and the explanations.

I totally understand from Adyen's point of view - internally. It is just very confusing when the latest documentation says something different, the library is v69 but communicates as v70 with the `/payment` - regardless of whether the field (still) works.

I pass this on in the team and we continue to use `deliveryDate` - with @ts-ignore annotated :)

We are not blocked by this - just puzzled and confused.

Thanks for shedding some light on this.
