### ISSUE TITLE
[BUG] Types missing in latest release?

### ISSUE THREAD

**Issue by VincentvD** [Adyen/adyen-node-api-library#694]
**Describe the bug**
Going from 7.0.0 to 8.1.0, some types are no longer exported (like ICheckout). Am I missing something or is this indeed broken?

**To Reproduce**
Use any type that was defined in ICheckout and update to 8.1.0

**Desktop (please complete the following information):**
 - OS: Macos
 - Node Version: v12.19.0
 - NPM Version: 6.14.8

**Comment by wboereboom** [comment]
Hi @VincentvD,

The ICheckout interface was replaced due to the type generation tool we now use.
All types that were previous in this interface can now still be found under `src/typings/checkout`.

This should not have any influence on the checkout service or any of its endpoints.

Kind regards,
Wouter
Adyen

**Comment by VincentvD** [comment]
Thanks for the swift response. I agree that the service and endpoints would not be effected. I can indeed use this:
```
import { Split } from '@adyen/api-library/lib/src/typings/checkout/models'
```
But it is not something I would expect so I wanted to verify this.

**Comment by wboereboom** [comment]
Note that we might remove more of the current interfaces as time goes on as new API versions are supported.
We're working on improving our release changes summary to avoid confusion and unexpected changes like this one in the future.

Thanks for raising this issue and Happy coding!
Wouter
Adyen
