### ISSUE TITLE
[PW-6908] Add support for split payment using the Terminal API

### ISSUE THREAD

**Issue by MahamdiAmine** [Adyen/adyen-node-api-library#920]
**Split configuration is not supported in API payment request**
the current implementation does not allow passing the split data in the payment request like the following example [Link](https://docs.adyen.com/platforms/platforms-for-pos#split-a-payment.)

**Describe the solution you'd like**
Allow passing the split data in `SaleToPOIRequest.PaymentRequest.SaleData.SaleToAcquirerData`

**Comment by jillingk** [comment]
Hi @MahamdiAmine,

Thanks for reaching out to us, I've created an internal ticket to pick this up. 

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @MahamdiAmine,

So after testing this it seems that we cannot easily make the functionality so that you can add the split data in the ```SaleToAcquirerData``` object. Instead we opted that merchants use the ```AdditionalData``` object in ```SaleToAcquirerData``` to send the split payment details in an array. I just tested this for myself and it works for me. 

So when creating your ```SaleToPOIRequest```, you should add something like this:

```
SaleToAcquirerData: {
                        additionalData: {"split.api": "1", "split.nrOfItems": "2","split.totalAmount": "10","split.currencyCode":"EUR","split.item1.amount":"3","split.item1.type":"MarketPlace","split.item1.account":"8815628270908491","split.item1.reference":"test1","split.item2.amount":"7","split.item2.type":"MarketPlace","split.item2.account":"8815628270908492","split.item2.reference":"test2"}
                    }
```

Sorry for the long delay with our answer, hope this helps! If there is anything else that we can help you with, please do let us know.

Best, Jilling
Adyen
